{% set version = "1.8.1" %}

package:
  name: sparqlwrapper
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SPARQLWrapper/SPARQLWrapper-{{ version }}.tar.gz
  sha256: da760be6f448f2030f2b4f7cecd4c55b0c2133458d5c420c50f78169db133e82

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - keepalive

test:
  imports:
    - SPARQLWrapper

about:
  home: https://github.com/RDFLib/sparqlwrapper
  license: W3C
  license_file: LICENSE.txt
  summary: 'SPARQL Endpoint interface to Python for use with rdflib'
  dev_url: https://github.com/RDFLib/sparqlwrapper
  doc_url: http://rdflib.github.io/sparqlwrapper

extra:
  recipe-maintainers:
    - satra
