{% set name = "SPARQLWrapper" %}
{% set version = "1.8.0" %}
{% set sha256 = "3b46d0f18ca0b65b8b965d6d1ae257b229388400b06e7dc19f0a51614dc1abde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - keepalive

test:
  imports:
    - SPARQLWrapper

about:
  home: https://github.com/RDFLib/sparqlwrapper
  license: W3C
  license_file: LICENSE.txt
  summary: 'SPARQL Endpoint interface to Python for use with rdflib'
  dev_url: https://github.com/RDFLib/sparqlwrapper
  doc_url: http://rdflib.github.io/sparqlwrapper

extra:
  recipe-maintainers:
    - satra
