travis:
  secure:
    BINSTAR_TOKEN: nYGHREa/87ipzYGMrfC9xGVigGltdMHgNiklpRfEWvj9VrnB8qUeBmiZaR+SntGpfjfxrAVQWO/VExBwzu5x8TCE3/klSyFzVh1sKj6sYsfbQl2qoWkOA5KWY7aCHNEHjcE9VUKgdcXK3Vom0JnJTKWlxj/RWzRfeatGJNqdtnMzYDBH2mEp3zXmkrY7XAWJrUCD2qtUYs2Se68O7zRMPb/4wxs5Il3mfH12QdJVF2dPRkP15uvVFtYgGJE0viq8wAgJmccV2HW+JFvW0oZyr81hlowNcTJFZsjtPN2CjFdVBS1wsBporJwmYjVakjUpm4jWzrENyxfR2/RWM3up2szdxLGCy49YJNpnO7VuHWMHtB9smgE3olnpI5B8StwjrOh+eWRgBXBa1UK3e8+s3wOthW6V2GmG9zU2rZ4LuRRbKE7OgcVEDuSt09BCkiFsPv2YtBTszYYHKKP5xQmQF5uyjDOiaHUcLn8u4elhZG5//GOgBveLU9ewtHX3/T3cmzGEPTmgOz9yh5hszhi0xOcWzEwfDdM3Lq8sV6cE+hQ3+LPqEsosiQKwaJKVjN2Pz/YHy1ABz9mrN9I00k6xQRnaUjOPgGquvEnE3hLSdwPxo+xpdjCdQmEsmDmeAQwZ2gMFL1cS656/RErOk7PhfpxbmWETTxYagLv8Rh9Bi7I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
